# Generated by Django 3.0.7 on 2021-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210426_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
