# Generated by Django 3.0.7 on 2021-04-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210426_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
    ]
